---
- hosts: auth_servers
  vars:
    domain_name: test.org
  remote_user: root
  tasks:
  - name: ensure OpenLDAP is at the latest version
    apt: pkg=slapd state=latest
    tags:
      - ldap
  - name: ensure LDAP-Utils is at the latest version
    apt: pkg=ldap-utils state=latest
    tags:
      - ldap
  - name: ensure isc-dhcp-server-ldap is at the latest version
    apt: pkg=isc-dhcp-server-ldap state=latest
    tags:
      - ldap
  - name: ensure postgresql-9.4 is at the latest version
    apt: pkg=postgresql-9.4 state=latest
    tags:
      - dns

  - name: copy kerberos.ldif
    copy: src=files/auth_servers/kerberos.ldif dest=/etc/ldap/schema/kerberos.ldif
    tags:
      - kerberos
  - name: copy dhcp.ldif
    copy: src=files/auth_servers/dhcp.ldif dest=/etc/ldap/schema/dhcp.ldif
    tags:
      - ldap
  - name: copy base OpenLDAP configuration
    template: src=templates/auth_servers/openldap_config.ldif dest=/etc/ldap/config.ldif
    tags:
      - ldap
  - name: copy OpenLDAP base content
    template: src=templates/auth_servers/openldap_base.ldif dest=/etc/ldap/base.ldif
    tags:
      - ldap
  - name: import cosine.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/cosine.ldif | true
    tags:
      - ldap
  - name: import nis.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/nis.ldif | true
    tags:
      - ldap
  - name: import inetorgperson.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/inetorgperson.ldif | true
    tags:
      - ldap
  - name: import kerberos.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/kerberos.ldif | true
    tags:
      - ldap
  - name: import dhcp.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/dhcp.ldif | true
    tags:
      - ldap
  - name: import base data
    shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/config.ldif
    tags:
      - ldap
  - name: import configuration
    shell: ldapadd -c -x -D cn=admin,{{ penates_domain|hostname_to_dn }} -w {{ ldap_root_password }} -f base.ldif | true
    tags:
      - ldap
  - name: restart OpenLDAP
    service: name=slapd state=restarted
    tags:
      - ldap
  - name: open TCP port for LDAP
    ufw: rule=allow port=636 proto=tcp
    tags:
      - ldap

  - name: ensure krb5-kdc-ldap is at the latest version
    apt: pkg=krb5-kdc-ldap state=latest
    tags:
      - kerberos
  - name: ensure krb5-kdc is at the latest version
    apt: pkg=krb5-kdc state=latest
    tags:
      - kerberos
  - name: ensure krb5-admin-server is at the latest version
    apt: pkg=krb5-admin-server state=latest
    tags:
      - kerberos
  - name: copy Kerberos LDAP password
    template: src=templates/auth_servers/service.keyfile dest=/etc/krb5kdc/service.keyfile
    tags:
      - kerberos
  - name: configure LDAP for Kerberos
    shell: kdb5_ldap_util -D cn=admin,{{ penates_domain|hostname_to_dn }} -w {{ ldap_root_password }} -H ldapi:/// create -subtrees cn=krbContainer,{{ penates_domain|hostname_to_dn }} -r {{ penates_domain|upper }} -P {{ kerberos_master_password }} -s | true
    tags:
      - kerberos
  - name: restart Kerberos admin
    service: name=krb5-admin-server state=restarted
    tags:
      - kerberos
  - name: restart Kerberos
    service: name=krb5-kdc state=restarted
    tags:
      - kerberos
  - name: open TCP port for Kerberos
    ufw: rule=allow port=88 proto=tcp
    tags:
      - kerberos
  - name: open UDP port for Kerberos
    ufw: rule=allow port=88 proto=udp
    tags:
      - kerberos
  - name: open TCP port for Kerberos admin
    ufw: rule=allow port=749 proto=tcp
    tags:
      - kerberos

  - name: ensure isc-dhcp-server is at the latest version
    apt: pkg=isc-dhcp-server state=latest
    tags:
      - dhcp
  - name: copy isc-dhcpd configuration
    template: src=templates/auth_servers/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
    tags:
      - dhcp
  - name: restart isc-dhcpd
    service: name=isc-dhcp-server state=restarted
    tags:
      - dhcp
  - name: restart isc-dhcpd6
    service: name=isc-dhcp-server6 state=restarted
    tags:
      - dhcp
  - name: open UDP port for DHCP
    ufw: rule=allow port=67 proto=udp
    tags:
      - dhcp
