---
- hosts: auth_servers
  remote_user: root
  vars:
    auth_fqdn: "directory{{ inventory_hostname|indexed_fqdn(groups['auth_servers']) }}.{{ penates_domain }}"
  tasks:
  - name: set the hostname
    template: src=templates/auth_servers/hostname dest=/etc/hostname owner=root group=root mode=0644
    tags:
      - powerdns
  - name: set the hostname
    command: hostname {{ penates_directory_hostname.partition('.')[0] }}
    tags:
      - powerdns

  - include: "include/postgresql.yml"
    vars:
      password: "{{ penatesserver_password }}"
      user: penatesserver
      database: penatesserver
    tags:
      - powerdns
      - penatesserver
  - include: "include/postgresql.yml"
    vars:
      password: "{{ powerdns_password }}"
      user: powerdns
      database: powerdns
    tags:
      - powerdns
      - pki

  - apt: pkg=python-pip
    tags:
      - penatesserver
  - apt: pkg=python-dev
    tags:
      - penatesserver
  - apt: pkg=libldap2-dev
    tags:
      - penatesserver
  - apt: pkg=libsasl2-dev
    tags:
      - penatesserver
  - name: create penatesserver user
    user: name=penatesserver home=/var/penatesserver createhome=yes
    tags:
      - penatesserver
  - pip: name=djangofloor
    tags:
      - penatesserver
  - pip: name=djangorestframework
    tags:
      - penatesserver
  - pip: name=netaddr
    tags:
      - penatesserver
  - pip: name=markdown
    tags:
      - penatesserver
  - pip: name=django-filter
    tags:
      - penatesserver
  - pip: name=pygments
    tags:
      - penatesserver
  - pip: name=django-ldapdb
    tags:
      - penatesserver
  - git: repo=https://github.com/d9pouces/Penates-Server.git
         dest=/var/penatesserver/src
         update=yes
    tags:
      - penatesserver
  - shell: python setup.py develop
    args:
      chdir: /var/penatesserver/src
    tags:
      - penatesserver
  - file: path=/var/penatesserver/data/pki/private state=directory owner=penatesserver
    tags:
      - penatesserver
  - file: path=/var/penatesserver/data/static state=directory owner=penatesserver
    tags:
      - penatesserver
  - file: path=/var/penatesserver/data/log state=directory owner=penatesserver
    tags:
      - penatesserver
  - file: path=/var/penatesserver/data/data/media state=directory owner=penatesserver
    tags:
      - penatesserver
  - file: path=/etc/penatesserver/ state=directory owner=penatesserver
    tags:
      - penatesserver
  - copy: src=private/ca_crt.pem dest=/var/penatesserver/data/pki/cacert.pem owner=penatesserver mode=0644 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/ca_key.pem dest=/var/penatesserver/data/pki/private/cakey.pem owner=penatesserver mode=0600 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/hosts_crt.pem dest=/var/penatesserver/data/pki/hosts_crt.pem owner=penatesserver mode=0644 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/hosts_key.pem dest=/var/penatesserver/data/pki/private/hosts_key.pem owner=penatesserver mode=0600 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/services_crt.pem dest=/var/penatesserver/data/pki/services_crt.pem owner=penatesserver mode=0644 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/services_key.pem dest=/var/penatesserver/data/pki/private/services_key.pem owner=penatesserver mode=0600 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/users_crt.pem dest=/var/penatesserver/data/pki/users_crt.pem owner=penatesserver mode=0644 group=penatesserver
    tags:
      - penatesserver
  - copy: src=private/users_key.pem dest=/var/penatesserver/data/pki/private/users_key.pem owner=penatesserver mode=0600 group=penatesserver
    tags:
      - penatesserver
  - name: copy PenatesServer configuration
    template: src=templates/auth_servers/penatesserver.ini dest=/etc/penatesserver/settings.ini owner=penatesserver group=penatesserver mode=0644
    tags:
      - penatesserver
  - copy: src=files/auth_servers/powerdns.sql dest=/tmp/powerdns.sql
    tags:
      - powerdns
      - pki
  - command: psql -d powerdns -X -h localhost -p 5432 -U powerdns -w -f /tmp/powerdns.sql
    environment:
      PGPASSWORD: "{{ powerdns_password }}"
    tags:
      - powerdns
      - pki
  - file: path=/tmp/powerdns.sql state=absent
    tags:
      - powerdns
      - pki
  - name: initialize PKI
    command: penatesserver-manage certificate --initialize {{ penates_domain }} CA
    sudo_user: penatesserver
    tags:
      - penatesserver
  - command: penatesserver-manage migrate
    sudo_user: penatesserver
    tags:
      - penatesserver
  - command: penatesserver-manage ensure_domain {{ penates_domain }}
    tags:
      - penatesserver
      - powerdns
  - command: "penatesserver-manage admin_user --password {{ penates_auth_password }} --permission administration {{ penates_auth_login }}"
  - command: "penatesserver-manage admin_user --password {{ penates_supervision_password }} --permission supervision {{ penates_supervision_login }}"
  - command: "penatesserver-manage admin_user --password {{ penates_dhcp_password }} --permission dhcp {{ penates_dhcp_login }}"

  - name: ensure OpenLDAP is at the latest version
    apt: pkg=slapd
    tags:
      - ldap
  - name: ensure LDAP-Utils is at the latest version
    apt: pkg=ldap-utils
    tags:
      - ldap
  - name: copy kerberos.ldif
    copy: src=files/auth_servers/kerberos.ldif dest=/etc/ldap/schema/kerberos.ldif
    tags:
      - kerberos
      - ldap
  - name: copy kerberos.ldif
    copy: src=files/auth_servers/asterisk.ldif dest=/etc/ldap/schema/asterisk.ldif
    tags:
      - ldap
      - asterisk
  - name: copy samba.ldif
    copy: src=files/auth_servers/samba.ldif dest=/etc/ldap/schema/samba.ldif
    tags:
      - ldap
  - name: copy overlay.ldif
    copy: src=files/auth_servers/overlay.ldif dest=/etc/ldap/schema/overlay.ldif
    tags:
      - ldap
  - name: copy base OpenLDAP configuration
    template: src=templates/auth_servers/openldap_config.ldif dest=/etc/ldap/config.ldif
    tags:
      - ldap
  - name: copy base OpenLDAP configuration
    template: src=files/auth_servers/openldap_indexes.ldif dest=/etc/ldap/indexes.ldif
    tags:
      - ldap
  - name: register LDAP service
    command: penatesserver-manage service ldaps {{ auth_fqdn }} 636 --fqdn {{ penates_directory_hostname }} --description "Main LDAP server" --cert /etc/ldap/slapd.d/{{ auth_fqdn }}.crt --key /etc/ldap/slapd.d/{{ auth_fqdn }}.key --encryption=tls
    tags:
      - ldap
  - name: copy OpenLDAP base content
    template: src=templates/auth_servers/openldap_base.ldif dest=/etc/ldap/base.ldif
    tags:
      - ldap
  - name: import cosine.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/cosine.ldif | true
    tags:
      - ldap
  - name: import nis.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/nis.ldif | true
    tags:
      - ldap
  - name: import inetorgperson.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/inetorgperson.ldif | true
    tags:
      - ldap
  - name: import kerberos.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/kerberos.ldif | true
    tags:
      - ldap
  - name: import asterisk.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/asterisk.ldif | true
    tags:
      - ldap
  - name: import samba.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/samba.ldif | true
    tags:
      - ldap
  - name: import base data
    shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/config.ldif
    tags:
      - ldap
  - name: import overlay.ldif
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/overlay.ldif | true
    tags:
      - ldap
  - name: import configuration
    shell: ldapadd -c -x -D cn=admin,{{ penates_domain|hostname_to_dn }} -w {{ ldap_root_password }} -H ldapi:///  -f /etc/ldap/base.ldif | true
    tags:
      - ldap
  - ufw: rule=allow port=636 proto=tcp
    tags:
      - ldap
  - file: path=/etc/ldap/config.ldif state=absent
    tags:
      - ldap
  - file: path=/etc/ldap/base.ldif state=absent
    tags:
      - ldap
  - lineinfile: dest=/etc/default/slapd regexp='SLAPD_SERVICES="ldap:/// ldapi:///"' line='SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"'
    tags:
      - ldap
  - file: path=/etc/ldap/slapd.d/{{ auth_fqdn }}.key state=file owner=openldap mode=0400 group=openldap
    tags:
      - ldap
  - name: restart OpenLDAP
    service: name=slapd state=restarted
    tags:
      - ldap
  - name: import base data
    shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/indexes.ldif
    tags:
      - ldap
  - file: path=/etc/ldap/indexes.ldif state=absent
    tags:
      - ldap
  - command: ldapsearch -x -H ldaps://{{ auth_fqdn }}/
    name: test ldaps:// interface
  - command: ldapsearch -x -H ldap://{{ auth_fqdn }}/
    name: test ldap:// interface
  - command: ldapsearch -x -H ldapi:///
    name: test ldapi:// interface
  - name: create base domain
    command: penatesserver-manage ensure_domain {{ penates_domain }}
    tags:
      - penatesserver
      - powerdns
      - ldap
  - name: register LDAP service
    command: penatesserver-manage service ldaps {{ auth_fqdn }} 636 --fqdn {{ penates_directory_hostname }} --description "Main LDAP server" --cert /etc/ldap/slapd.d/{{ auth_fqdn }}.crt --key /etc/ldap/slapd.d/{{ auth_fqdn }}.key --encryption=tls
    tags:
      - ldap

  - apt: pkg=heimdal-kdc
    tags:
      - kerberos
  - apt: pkg=heimdal-kcm
    tags:
      - kerberos
  - name: register Kerberos service
    command: penatesserver-manage service krb {{ auth_fqdn }} 88 --role "Kerberos DC" --fqdn {{ penates_directory_hostname }} --description "Main Kerberos server" --cert /var/lib/heimdal-kdc/{{ auth_fqdn }}.crt --key /var/lib/heimdal-kdc/{{ auth_fqdn }}.key --srv tcp/kerberos
    tags:
      - kerberos
  - name: register Kerberos UDP service
    command: penatesserver-manage service krb {{ auth_fqdn }} 88 --role "Kerberos DC" --fqdn {{ penates_directory_hostname }} --description "Main Kerberos server" --protocol udp --srv tcp/kerberos
    tags:
      - kerberos
  - name: copy Kerberos KDC configuration
    template: src=templates/auth_servers/kdc.conf dest=/var/lib/heimdal-kdc/kdc.conf
    tags:
      - kerberos
  - name: copy Kerberos admin
    template: src=templates/auth_servers/kadmind.acl dest=/etc/heimdal-kdc/kadmind.acl
    tags:
      - kerberos
  - shell: kadmin -l init --realm-max-ticket-life=1d --realm-max-renewable-life=1w {{ penates_domain|upper }} | true
    tags:
      - kerberos
  - name: restart Kerberos admin
    service: name=heimdal-kcm state=restarted
    tags:
      - kerberos
  - name: restart Kerberos
    service: name=heimdal-kdc state=restarted
    tags:
      - kerberos
  - service: name=openbsd-inetd state=restarted
    tags:
      - kerberos
  - ufw: rule=allow port=88 proto=tcp
    tags:
      - kerberos
  - ufw: rule=allow port=88 proto=udp
    tags:
      - kerberos
  - shell: kadmin -l add --random-key --max-ticket-life=1d --max-renewable-life=1w --expiration-time=never --attributes= --pw-expiration-time=never --policy=default penatesserver/admin | true

  - name: remove keytab for PenatesServer
    file: path=/var/penatesserver/data/pki/private/kadmin.keytab state=absent
    tags:
      - penatesserver
      - kerberos
  - name: export to keytab for PenatesServer
    command: kadmin -l ext_keytab -k /var/penatesserver/data/pki/private/kadmin.keytab penatesserver/admin
    tags:
      - penatesserver
      - kerberos
  - command: kinit -t /var/penatesserver/data/pki/private/kadmin.keytab -k penatesserver/admin
    tags:
      - penatesserver
      - kerberos
  - file: path=/var/penatesserver/data/pki/private/kadmin.keytab state=file owner=penatesserver group=penatesserver mode=0600
    tags:
      - penatesserver
      - kerberos
#  - include: include/apache.yml
  - apt: pkg=apache2
    tags:
      - penatesserver
  - apt: pkg=libapache2-mod-xsendfile
    tags:
      - penatesserver
  - apt: pkg=libapache2-mod-auth-kerb
    tags:
      - penatesserver
  - apache2_module: state=present name=auth_kerb
    tags:
      - penatesserver
  - apache2_module: state=present name=headers
    tags:
      - penatesserver
  - apache2_module: state=present name=proxy
    tags:
      - penatesserver
  - apache2_module: state=present name=proxy_http
    tags:
      - penatesserver
  - apache2_module: state=present name=ssl
    tags:
      - penatesserver
  - command: penatesserver-manage collectstatic --noinput
    sudo_user: penatesserver
    tags:
      - penatesserver
  - name: register HTTP service
    command: penatesserver-manage service http {{ auth_fqdn }} 443 --role "Service" --fqdn {{ penates_directory_hostname }} --description "Penates Webservices" --kerberos_service HTTP --keytab /etc/apache2/http.keytab --cert /etc/apache2/{{ auth_fqdn }}.pem --key /etc/apache2/{{ auth_fqdn }}.pem --ca /etc/apache2/{{ auth_fqdn }}.pem --encryption=tls
    tags:
      - penatesserver
  - command: kinit -t /etc/apache2/http.keytab -k HTTP/{{ penates_directory_hostname }}@{{ penates_domain|upper }}
    tags:
      - penatesserver
      - kerberos
  - file: path=/var/penatesserver/data state=directory owner=penatesserver recurse=yes group=penatesserver
    tags:
      - penatesserver
  - file: path=/etc/apache2/http.keytab state=file owner=www-data group=www-data mode=0600
    tags:
      - penatesserver
  - file: path=/etc/apache2/{{ auth_fqdn }}.pem state=file owner=www-data group=www-data mode=0600
    tags:
      - penatesserver
  - template: src=templates/auth_servers/penatesserver.conf dest=/etc/apache2/sites-available/{{ auth_fqdn }}.conf owner=www-data group=www-data mode=0644
    tags:
      - penatesserver
  - file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    tags:
      - penatesserver
  - file: path=/etc/apache2/sites-enabled/000-default state=absent
    tags:
      - penatesserver
  - file: path=/etc/apache2/sites-enabled/{{ auth_fqdn }}.conf src=/etc/apache2/sites-available/{{ auth_fqdn }}.conf state=link
    tags:
      - penatesserver
  - name: copy penatesserver systemd configuration
    template: src=templates/auth_servers/penatesserver-systemd.service dest=/etc/systemd/system/penatesserver-gunicorn.service
    tags:
      - penatesserver
  - service: name=apache2 state=restarted
    tags:
      - penatesserver
  - command: systemctl enable penatesserver-gunicorn.service
    tags:
      - penatesserver
  - service: name=penatesserver-gunicorn state=restarted
    tags:
      - penatesserver
  - ufw: rule=allow port=443 proto=tcp
    tags:
      - penatesserver

  - apt: pkg=pdns-backend-pgsql
    tags:
      - powerdns
  - apt: pkg=dnsutils
    tags:
      - powerdns
  - apt: pkg=pdns-server
    tags:
      - powerdns
  - apt: pkg=pdns-recursor
    tags:
      - powerdns
  - template: src=templates/auth_servers/pdns.conf dest=/etc/powerdns/pdns.conf owner=pdns group=pdns mode=0644
    tags:
      - powerdns
  - template: src=templates/auth_servers/recursor.conf dest=/etc/powerdns/recursor.conf owner=pdns group=pdns mode=0644
    tags:
      - powerdns
  - service: name=pdns state=restarted
    tags:
      - powerdns
  - service: name=pdns-recursor state=restarted
    tags:
      - powerdns
  - ufw: rule=allow port=53 proto=udp
    tags:
      - powerdns
  - name: register DNS service
    command: penatesserver-manage service dns {{ auth_fqdn }} 53 --role "Service" --fqdn {{ penates_directory_hostname }} --description "Main DNS server" --protocol udp
    tags:
      - powerdns
  - shell: "pdnssec secure-zone {{ penates_domain }} | true"
    tags:
      - powerdns
  - template: src=templates/auth_servers/main_network_interface.cfg dest=/etc/network/interfaces.d/{{ primary_network_interface }}.cfg owner=root group=root mode=0644
    tags:
      - networking

  - lineinfile: regexp='iface\s+{{ primary_network_interface }}\s+inet\s+dhcp\s*' state=absent dest=/etc/network/interfaces
    tags:
      - networking
  - lineinfile: regexp='auto\s+{{ primary_network_interface }}\s*' state=absent dest=/etc/network/interfaces
    tags:
      - networking
  - service: name=networking state=restarted
    tags:
      - networking

  - command: penatesserver-manage group {{ penates_administrators_group }}
    tags:
      - penatesserver
  - command: penatesserver-manage group {{ penates_guests_group }}
    tags:
      - penatesserver
  - command: penatesserver-manage group {{ penates_users_group }}
    tags:
      - penatesserver

  - command: penatesserver-manage user {{ penates_admin_name }} --password {{ penates_admin_password }} --group {{ penates_administrators_group }} --group {{ penates_users_group }}
    tags:
      - penatesserver
      - users
  - command: penatesserver-manage user {{ penates_user_name }} --password {{ penates_user_password }} --group {{ penates_users_group }}
    tags:
      - penatesserver
      - users
  - shell: echo {{ penates_admin_password }} | kinit  --password-file=STDIN  {{ penates_admin_name }}@{{ penates_domain|upper }}
    tags:
      - users
  - command: "curl --anyauth -u : -o /tmp/admin.pem https://{{ penates_directory_fqdn }}/auth/get_user_certificate/"
    tags:
      - users
  - command: kdestroy
    tags:
      - users
  - command: kinit -C FILE:/tmp/admin.pem {{ penates_admin_name }}@{{ penates_domain|upper }}
    tags:
      - users
  - command: kdestroy
    tags:
      - users
  - file: path=/tmp/admin.pem state=absent
    tags:
      - users
