---
- hosts: all_machines
  remote_user: root
  vars:
    lang_env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LC_TYPE: en_US.UTF-8
  tasks:
  - command: ifconfig
    environment: lang_env
    register: ifconfig
  - set_fact: network_config="{{ ifconfig.stdout|penates_ifconfig(server=penates_server_subnet, admin=penates_admin_subnet, client=penates_client_subnet) }}"
  - set_fact: infra_fqdn="{{ ansible_nodename }}.infra.{{ penates_domain }}"
  - set_fact: admin_fqdn="{{ ansible_nodename }}.admin.{{ penates_domain }}"
  - stat: path=/etc/host.keytab
    register: check_host_keytab
  - command: "curl -o /etc/host.keytab https://{{ penates_directory_fqdn }}/no-auth/get_host_keytab/{{ infra_fqdn }}"
    when: check_host_keytab.stat.exists == False
  - file: path=/etc/host.keytab owner=root mode=0600 group=root
  - command: ktutil -k /etc/host.keytab list
  - shell: "ifconfig | grep -B 2 `k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/get_info/ | grep REMOTE_ADDR | cut -f 2 -d ':'` | grep HWaddr | cut -d 'H' -f 2 | cut -d ' ' -f 2"
    register: primary_mac_address
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_dhcp/{{ primary_mac_address.stdout }}/?mac_address={{ network_config|ifcache('admin', 1) }}&ip_address={{ network_config|ifcache('admin', 2) }}"

  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/ssh/{{ admin_fqdn }}/22/?keytab=host&srv=tcp/ssh"
  - command: "k5start -q -f /etc/host.keytab -U -- curl -o /etc/krb5.keytab --anyauth -u : https://{{ penates_directory_fqdn }}/auth/get_service_keytab/ssh/{{ admin_fqdn }}/22/"
  - file: path=/etc/krb5.keytab owner=root mode=0600 group=root
  - command: ktutil -k /etc/krb5.keytab list
  - command: "k5start -q -f /etc/host.keytab -U -- curl -o /etc/ssl/private/host.pem --anyauth -u : https://{{ penates_directory_fqdn }}/auth/get_host_certificate/"
  - file: path=/etc/ssl/private/host.pem owner=root mode=0600 group=root
  - command: "openssl x509 -in /etc/ssl/private/host.pem -out /etc/host.pem"
  - command: "k5start -q -f /etc/host.keytab -U -- curl --data-binary @/etc/ssh/ssh_host_ecdsa_key.pub --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_ssh_pub/"
  - command: "k5start -q -f /etc/host.keytab -U -- curl --data-binary @/etc/ssh/ssh_host_ed25519_key.pub --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_ssh_pub/"
  - command: "k5start -q -f /etc/host.keytab -U -- curl --data-binary @/etc/ssh/ssh_host_rsa_key.pub --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_ssh_pub/"
  - name: hosts configuration
    template: src=templates/common/hosts dest=/etc/hosts

  - apt: pkg=ntp
    tags:
      - ntp
  - template: src=templates/common/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
    tags:
      - ntp
  - service: name=ntp state=restarted
    tags:
      - ntp

  - apt: pkg=krb5-pkinit
    tags:
      - authent
  - apt: pkg=libnss-ldapd
    tags:
      - authent
  - apt: pkg=libpam-heimdal
    tags:
      - authent
  - apt: pkg=libpam-ccreds
    tags:
      - authent
  - template: src=templates/common/nslcd.conf dest=/etc/nslcd.conf
    tags:
      - authent
  - template: src=templates/common/nsswitch.conf dest=/etc/nsswitch.conf
    tags:
      - authent
  - template: src=templates/common/access.conf dest=/etc/security/access.conf
    tags:
      - authent
  - template: src=templates/common/sudoers dest=/etc/sudoers mode=0440 owner=root group=root
    tags:
      - authent
  - template: src=templates/common/sshd_config dest=/etc/ssh/sshd_config
    tags:
      - authent
  - template: src=templates/common/pam.d/common-session dest=/etc/pam.d/common-session
    tags:
      - authent
  - service: name=ssh state=restarted
    tags:
      - authent
  - service: name=nslcd state=restarted
    tags:
      - authent
  - service: name=nscd state=restarted
    tags:
      - authent
  - apt: pkg=snmp
    tags:
      - snmp
  - apt: pkg=snmpd
    tags:
      - snmp
  - template: src=templates/common/snmp/snmp.conf dest=/etc/snmp/snmp.conf
    tags:
      - snmp
  - template: src=templates/common/snmp/snmpd.conf dest=/etc/snmp/snmpd.conf
    tags:
      - snmp
  - template: src=templates/common/snmp/snmptrapd.conf dest=/etc/snmp/snmptrapd.conf
    tags:
      - snmp
  - ufw: rule=allow port=161 proto=udp
  - service: name=snmpd state=restarted
    tags:
      - snmp

  - apt: pkg=clamav
    tags:
      - antivirus
  - apt: pkg=clamav-daemon
    tags:
      - antivirus
  - template: src=templates/common/clamd.conf dest=/etc/clamav/clamd.conf
    tags:
      - antivirus
  - template: src=templates/common/freshclam.conf dest=/etc/clamav/freshclam.conf
    tags:
      - antivirus
  - cron: hour=2 job="/usr/bin/freshclam >/dev/null" minute=0 name="ClamAV"
    tags:
      - antivirus
  - service: name=clamav-daemon state=restarted
    tags:
      - antivirus


- hosts: dhcp_servers
  remote_user: root
  tasks:
  - apt: pkg=isc-dhcp-server
    tags:
      - dhcp
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : -o /etc/dhcp/dhcpd.conf https://{{ penates_directory_fqdn }}/auth/conf/dhcpd.conf"
    tags:
      - dhcp
  - service: name=isc-dhcp-server state=restarted
    tags:
      - dhcp
  - service: name=isc-dhcp-server6 state=restarted
    tags:
      - dhcp


- hosts: auth_servers
  remote_user: root
  tasks:
  - service: name=pdns-recursor state=restarted
    tags:
      - dhcp
