---
- hosts: all_machines
  remote_user: root
  tasks:
  - apt: pkg=ufw state=latest
  - ufw: rule=limit port=ssh proto=tcp
  - ufw: state=enabled
  - ufw: policy=deny direction=incoming
  - copy: src=files/common/sources.list dest=/etc/apt/sources.list owner=root mode=0644 group=root
  - command: apt-get update
  - apt: pkg=heimdal-clients state=latest
  - apt: pkg=kstart state=latest
  - apt: pkg=curl state=latest
  - template: src=templates/common/krb5.conf dest=/etc/krb5.conf
  - template: src=templates/common/ldap.conf dest=/etc/ldap/ldap.conf
  - apt: pkg=vim state=latest
  - template: src=templates/common/hosts dest=/etc/hosts
  - apt: pkg=ca-certificates state=latest
  - name: CA root certificate (1/2)
    template: src=files/auth_servers/ca_cert.pem dest=/etc/ssl/certs/Penates_CA.pem mode=0644
  - name: CA root certificate (2/2)
    template: src=files/auth_servers/ca_cert.pem dest=/usr/share/ca-certificates/Penates_CA.crt mode=0644
  - name: config CA root certificate
    lineinfile: dest=/etc/ca-certificates.conf line=Penates_CA.crt state=present
  - name: Update CA certificates (1/2)
    command: c_rehash /etc/ssl/certs
  - name: Update CA certificates (2/2)
    command: update-ca-certificates
  - apt: pkg=rsyslog
  - apt: pkg=rsyslog-gnutls
  - file: path=/var/log/local/auth.log state=touch owner=syslog group=adm
  - file: path=/var/log/local/ state=directory owner=syslog group=adm
  - template: src=templates/common/rsyslog.d/20-ufw.conf dest=/etc/rsyslog.d/20-ufw.conf
  - template: src=templates/common/rsyslog.d/50-default.conf dest=/etc/rsyslog.d/50-default.conf
  - template: src=templates/common/rsyslog.d/90-penates.conf dest=/etc/rsyslog.d/90-penates.conf
  - service: name=rsyslog state=restarted
  - apt: pkg=python-pyinotify
  - apt: pkg=fail2ban
  - template: src=templates/common/fail2ban.conf dest=/etc/fail2ban/jail.local
  - service: name=fail2ban state=restarted
