---
- hosts: dhcp_servers
  remote_user: root
  vars:
    dhcp_fqdn: "dhcp{{ inventory_hostname|indexed_fqdn(groups['dhcp_servers']) }}.{{ penates_domain }}"
  tasks:

  - apt: pkg=dhcping
    tags:
      - dhcp
  - apt: pkg=isc-dhcp-server
    tags:
      - dhcp
  - name: copy isc-dhcpd configuration
    template: src=templates/dhcp_servers/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
    tags:
      - dhcp
#  - lineinfile: regexp="    exec dhcpd -user dhcpd -group dhcpd -f -4 -pf /run/dhcp-server/dhcpd.pid -cf $CONFIG_FILE $INTERFACES" dest=/etc/systemd/system/multi-user.target.wants/isc-dhcp-server.service line="    exec dhcpd -user dhcpd -group dhcpd -f -4 -pf /var/run/dhcp-server/dhcpd.pid -cf $CONFIG_FILE $INTERFACES"
#    tags:
#      - dhcp
#  - lineinfile: regexp="    exec dhcpd -user dhcpd -group dhcpd -f -6 -pf /run/dhcp-server/dhcpd6.pid -cf $CONFIG_FILE $INTERFACES" dest=/etc/systemd/system/multi-user.target.wants/isc-dhcp-server6.service line="    exec dhcpd -user dhcpd -group dhcpd -f -4 -pf /var/run/dhcp-server/dhcpd6.pid -cf $CONFIG_FILE $INTERFACES"
#    tags:
#      - dhcp
  - command: systemctl daemon-reload
    tags:
      - dhcp
  - service: name=isc-dhcp-server state=restarted
    tags:
      - dhcp
  - service: name=isc-dhcp-server6 state=restarted
    tags:
      - dhcp
  - ufw: rule=allow port=67 proto=udp
    tags:
      - dhcp
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/dhcp/{{ dhcp_fqdn }}/67/?role=Service&protocol=udp"
    tags:
      - dhcp
