---
- hosts: dhcp_servers
  remote_user: root
  vars:
    dhcp_fqdn: "dhcp{{ inventory_hostname|indexed_fqdn(groups['dhcp_servers']) }}.{{ penates_domain }}"
  tasks:
  - apt: pkg=dhcping
  - apt: pkg=isc-dhcp-server
  - name: copy isc-dhcpd configuration
  - file: path=/var/scripts owner=root mode=0755 group=root state=directory
  - template: src=templates/dhcp_servers/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  - template: src=templates/dhcp_servers/dhcp.sh dest=/var/scripts/dhcp.sh mode=0755
#  - lineinfile: regexp="    exec dhcpd -user dhcpd -group dhcpd -f -4 -pf /run/dhcp-server/dhcpd.pid -cf $CONFIG_FILE $INTERFACES" dest=/etc/systemd/system/multi-user.target.wants/isc-dhcp-server.service line="    exec dhcpd -user dhcpd -group dhcpd -f -4 -pf /var/run/dhcp-server/dhcpd.pid -cf $CONFIG_FILE $INTERFACES"
#  - lineinfile: regexp="    exec dhcpd -user dhcpd -group dhcpd -f -6 -pf /run/dhcp-server/dhcpd6.pid -cf $CONFIG_FILE $INTERFACES" dest=/etc/systemd/system/multi-user.target.wants/isc-dhcp-server6.service line="    exec dhcpd -user dhcpd -group dhcpd -f -4 -pf /var/run/dhcp-server/dhcpd6.pid -cf $CONFIG_FILE $INTERFACES"
  - command: systemctl daemon-reload
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : -o /etc/dhcp/dhcpd.conf https://{{ penates_directory_fqdn }}/auth/conf/dhcpd.conf"
  - service: name=isc-dhcp-server state=restarted
  - service: name=isc-dhcp-server6 state=restarted
  - ufw: rule=allow port=67 proto=udp
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/dhcp/{{ dhcp_fqdn }}/67/?role=Service&protocol=udp"
  - cron: job=/var/scripts/dhcp.sh name='restart dhcp' minute=0
