---

- hosts: log_servers
  remote_user: root
  vars:
    sup_fqdn: "sup{{ inventory_hostname|indexed_fqdn(groups['supervision_servers']) }}.{{ penates_domain }}"
    sup_sqdn: "sup{{ inventory_hostname|indexed_fqdn(groups['supervision_servers']) }}"
  tasks:
  - command: hostname
    register: actual_hostname
  - apt: pkg=shinken-mod-pickle-retention-file-generic
  - apt: pkg=shinken-mod-webui
  - apt: pkg=shinken-core
#  - apt: pkg=shinken-mod-ui-graphite
#  - apt: pkg=shinken-mod-graphite
  - apt: pkg=shinken-mod-booster-nrpe
  - apt: pkg=shinken-mod-hot-dependencies
  - apt: pkg=shinken-mod-logstore-sqlite
  - apt: pkg=nagios-plugins-basic
  - file: path=/var/lib/shinken/inventory state=directory
  - file: path=/var/lib/shinken/doc state=directory
  - file: path=/var/lib/shinken/share state=directory
  - file: path=/var/lib/shinken/inventory state=directory
  - template: src=templates/supervision_servers/shinken.ini dest=/root/.shinken.ini mode=0644

  - template: src=templates/supervision_servers/contacts.cfg dest=/etc/shinken/contacts.cfg mode=0644
  - template: src=templates/supervision_servers/resource.cfg dest=/etc/shinken/resource.cfg mode=0644
  - template: src=templates/supervision_servers/shinken.cfg dest=/etc/shinken/shinken.cfg mode=0644


  - template: src=templates/supervision_servers/schedulers/scheduler.cfg dest=/etc/shinken/schedulers/scheduler.cfg mode=0644
  - template: src=templates/supervision_servers/daemons/schedulerd.ini dest=/etc/shinken/daemons/schedulerd.ini mode=0644
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/http/{{ sup_fqdn }}/7768/?encryption=tls"
  - ufw: rule=allow port=7768 proto=tcp

  - template: src=templates/supervision_servers/reactionners/reactionner.cfg dest=/etc/shinken/reactionners/reactionner.cfg mode=0644
  - template: src=templates/supervision_servers/daemons/reactionnerd.ini dest=/etc/shinken/daemons/reactionnerd.ini mode=0644
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/http/{{ sup_fqdn }}/7769/?encryption=tls"
  - ufw: rule=allow port=7769 proto=tcp

  - template: src=templates/supervision_servers/arbiters/arbiter.cfg dest=/etc/shinken/arbiters/arbiter.cfg mode=0644
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/http/{{ sup_fqdn }}/7770/?encryption=tls"
  - ufw: rule=allow port=7770 proto=tcp

  - template: src=templates/supervision_servers/pollers/poller.cfg dest=/etc/shinken/pollers/poller.cfg mode=0644
  - template: src=templates/supervision_servers/daemons/pollerd.ini dest=/etc/shinken/daemons/pollerd.ini mode=0644
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/http/{{ sup_fqdn }}/7771/?encryption=tls"
  - ufw: rule=allow port=7771 proto=tcp

  - template: src=templates/supervision_servers/brokers/broker.cfg dest=/etc/shinken/brokers/broker.cfg mode=0644
  - template: src=templates/supervision_servers/daemons/brokerd.ini dest=/etc/shinken/daemons/brokerd.ini mode=0644
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/http/{{ sup_fqdn }}/7772/?encryption=tls"
  - ufw: rule=allow port=7772 proto=tcp

  - template: src=templates/supervision_servers/receivers/receiver.cfg dest=/etc/shinken/receivers/receiver.cfg mode=0644
  - template: src=templates/supervision_servers/daemons/receiverd.ini dest=/etc/shinken/daemons/receiverd.ini mode=0644
  - command: "k5start -q -f /etc/host.keytab -U -- curl --anyauth -u : https://{{ penates_directory_fqdn }}/auth/set_service/http/{{ sup_fqdn }}/7773/?encryption=tls"
  - ufw: rule=allow port=7773 proto=tcp

  - command: "k5start -q -f /etc/host.keytab -U -- curl -o /etc/shinken/shinken.pem --anyauth -u : https://{{ penates_directory_fqdn }}/auth/get_service_certificate/http/{{ sup_fqdn }}/7770/"
  - command: "openssl x509 -in /etc/shinken/shinken.pem -out /etc/shinken/shinken.crt"
  - command: "openssl rsa -in /etc/shinken/shinken.pem -out /etc/shinken/shinken.key"
  - file: path=/etc/shinken/shinken.pem mode=0400
  - file: path=/etc/shinken/shinken.key mode=0400

  - template: src=templates/supervision_servers/modules/webui.cfg dest=/etc/shinken/modules/webui.cfg mode=0644
  - template: src=templates/supervision_servers/modules/import-glpi.cfg dest=/etc/shinken/modules/import-glpi.cfg mode=0644
  - command: shinken-arbiter -v -c /etc/shinken/shinken.cfg

  - command: shinken install import-glpi
  - command: shinken install logstore-sqlite
  - command: shinken install livestatus

  - service: name=shinken state=restarted
  - ufw: rule=allow port=80 proto=tcp

  - include: "include/apache.yml"
    vars:
      apache_conf_template: templates/supervision_servers/shinken.conf
      server_fqdn: "{{ sup_fqdn }}"

#  - apt: pkg=graphite-web
#  - apt: pkg=graphite-carbon
#  - template: src=templates/supervision_servers/graphite_settings.py dest=/etc/graphite/local_settings.py mode=0644
#  - template: src=templates/supervision_servers/carbon_settings.ini dest=/etc/carbon/carbon.conf mode=0644
#  - include: "include/postgresql.yml"
#    vars:
#      user: graphite
#      database: graphite
#      password: "{{ graphite_password }}"
#  - command: graphite-manage syncdb

- hosts: all_machines
  remote_user: root
